In [3]:
import pandas as pd
import numpy as np

In [4]:
airbnb = pd.read_csv('paris_airbnb.csv')

In [5]:
airbnb

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173
2,100%,NaN,2.0,48.85758,2.35275,Paris,75004,Île-de-France,4,Entire home/apt,2.0,1.0,2.0,$115.00,$50.00,$200.00,10,23,243
3,100%,NaN,1.0,48.86528,2.39326,Paris,75020,Ile-de-France,3,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,365,1
4,67%,NaN,3.0,48.85899,2.34735,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$200.00,"$1,500.00",180,365,0
5,100%,NaN,1.0,48.86227,2.37134,Paris,75011,Ile-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$20.00,$250.00,5,120,17
6,NaN,NaN,4.0,48.88902,2.34656,Paris,75018,Ile-de-France,4,Entire home/apt,NaN,1.0,1.0,$80.00,$36.00,$800.00,90,730,42
7,NaN,NaN,4.0,48.88918,2.34490,Paris,75018,Ile-de-France,3,Entire home/apt,NaN,1.0,1.0,$75.00,NaN,$400.00,30,730,16
8,100%,NaN,1.0,48.87900,2.31608,Paris,75008,Ile-de-France,4,Entire home/apt,1.0,1.0,2.0,$90.00,$60.00,$600.00,3,730,40
9,100%,NaN,2.0,48.84670,2.35095,Paris,75005,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$75.00,NaN,NaN,2,1125,336
10,74%,NaN,2.0,48.87110,2.37424,Paris,75011,Île-de-France,6,Entire home/apt,1.0,1.0,3.0,$157.00,NaN,NaN,1,730,116
11,100%,NaN,1.0,48.88434,2.34005,Paris,75018,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$100.00,$80.00,$600.00,7,90,13
12,75%,NaN,1.0,48.86350,2.36961,Paris,75011,Ile-de-France,2,Entire home/apt,NaN,1.0,1.0,$70.00,$60.00,"$1,000.00",7,730,2
13,100%,NaN,1.0,48.82405,2.36828,Paris,75013,Île-de-France,3,Entire home/apt,1.0,1.0,1.0,$110.00,$30.00,$600.00,2,20,78
14,90%,NaN,1.0,48.86578,2.37705,Paris,75011,Ile-de-France,3,Entire home/apt,0.0,1.0,2.0,$79.00,$25.00,$500.00,30,305,312
15,NaN,NaN,2.0,48.85090,2.38695,Paris,75011,Ile-de-France,2,Private room,1.0,1.0,1.0,$60.00,$20.00,$80.00,6,40,1
16,100%,NaN,1.0,48.85909,2.37704,Paris,75011,Île-de-France,4,Entire home/apt,2.0,1.0,3.0,$100.00,$50.00,$500.00,5,90,11
17,60%,NaN,1.0,48.88315,2.34158,Paris,75018,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$110.00,$30.00,$500.00,7,365,9
18,NaN,NaN,1.0,48.89052,2.34453,Paris,75018,IDF,3,Entire home/apt,0.0,1.0,0.0,$75.00,$20.00,$0.00,3,120,200
19,100%,NaN,2.0,48.83616,2.36323,Paris,75013,Ile-de-France,5,Entire home/apt,1.0,1.0,3.0,$55.00,$50.00,$250.00,4,730,23
20,100%,NaN,2.0,48.85339,2.36284,Paris,75004,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$78.00,$30.00,$250.00,5,9,339
21,100%,NaN,9.0,48.85324,2.34171,Paris,75006,Ile-de-France,4,Private room,1.0,1.5,2.0,$100.00,$75.00,$400.00,5,730,66
22,90%,NaN,3.0,48.87033,2.37152,Paris,75010,Ile-de-France,4,Entire home/apt,2.0,1.0,2.0,$105.00,$30.00,$300.00,2,20,59
23,100%,NaN,1.0,48.87217,2.36206,Paris,75010,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$80.00,$60.00,$500.00,120,1125,1
24,100%,NaN,2.0,48.88282,2.33272,Paris,75009,Île-de-France,3,Entire home/apt,2.0,1.0,2.0,$110.00,NaN,$200.00,2,15,3
25,100%,NaN,2.0,48.88327,2.33292,Paris,75009,Île-de-France,1,Private room,1.0,1.5,1.0,$65.00,NaN,NaN,1,10,113
26,100%,NaN,1.0,48.86093,2.34254,Paris,75001,Ile-de-France,2,Entire home/apt,1.0,1.5,1.0,$250.00,NaN,"$2,500.00",3,730,154
27,100%,NaN,2.0,48.89001,2.34584,Paris,75018,Ile-de-France,4,Entire home/apt,1.0,1.0,2.0,$113.00,$49.00,$600.00,2,90,18
28,59%,NaN,2.0,48.88308,2.33283,Paris,75009,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$49.00,$50.00,$100.00,7,1125,82
29,100%,NaN,1.0,48.88565,2.35906,Paris,75018,Ile-de-France,3,Entire home/apt,1.0,1.0,2.0,$80.00,NaN,$200.00,3,14,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,NaN,NaN,1.0,48.86816,2.38444,Paris,75020,Île-de-France,2,Private room,1.0,1.0,1.0,$60.00,NaN,NaN,1,16,0
7971,NaN,NaN,1.0,48.88212,2.34903,Paris,75009,Île-de-France,8,Entire home/apt,3.0,1.0,4.0,$180.00,$30.00,$300.00,2,6,1
7972,100%,NaN,1.0,48.85750,2.27467,Paris,75016,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$15.00,$500.00,2,1125,17
7973,100%,NaN,1.0,48.82203,2.32209,Paris,75014,Île-de-France,4,Entire home/apt,2.0,1.0,3.0,$95.00,$30.00,$250.00,8,120,15
7974,NaN,NaN,1.0,48.87130,2.39275,Paris,75020,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$80.00,NaN,NaN,1,1125,0
7975,NaN,NaN,1.0,48.86606,2.33127,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$140.00,$60.00,$200.00,1,1125,0
7976,50%,NaN,1.0,48.84375,2.34960,Paris,75005,Île-de-France,5,Entire home/apt,3.0,2.0,5.0,$200.00,NaN,NaN,4,30,0
7977,NaN,NaN,1.0,48.86218,2.40732,Paris,75020,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$85.00,$20.00,NaN,5,14,9
7978,100%,NaN,1.0,48.87562,2.38388,Paris,75019,Île-de-France,5,Entire home/apt,2.0,1.0,4.0,$110.00,$50.00,$700.00,3,1125,33
7979,NaN,NaN,1.0,48.84657,2.38435,Paris,75012,Île-de-France,4,Entire home/apt,1.0,1.0,3.0,$120.00,$0.00,$0.00,3,1125,11
7980,33%,NaN,1.0,48.84841,2.37941,Paris,75011,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$50.00,$15.00,$0.00,3,7,75
7981,100%,NaN,1.0,48.87573,2.34558,Paris,75009,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$55.00,$30.00,$400.00,1,7,204
7982,NaN,NaN,1.0,48.85511,2.33901,Paris,75006,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$68.00,$100.00,$0.00,7,100,12
7983,100%,NaN,1.0,48.86697,2.36327,Paris,75003,Île-de-France,2,Private room,1.0,1.5,1.0,$32.00,$30.00,$200.00,7,30,4
7984,NaN,NaN,1.0,48.87203,2.30208,Paris,75008,Île-de-France,5,Entire home/apt,3.0,2.0,3.0,$360.00,NaN,"$1,000.00",5,1125,2
7985,NaN,NaN,1.0,48.88641,2.33871,Paris,75018,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$60.00,$20.00,$700.00,1,1125,5
7986,NaN,NaN,1.0,48.86606,2.34847,Paris,75002,Île-de-France,5,Entire home/apt,2.0,1.0,2.0,$150.00,$50.00,$400.00,4,60,15
7987,100%,NaN,1.0,48.85442,2.37354,Paris,75011,Île-de-France,4,Entire home/apt,1.0,1.0,2.0,$79.00,$20.00,$200.00,3,1125,40
7988,100%,NaN,2.0,48.83111,2.35257,Paris,75013,IDF,4,Entire home/apt,0.0,1.0,1.0,$98.00,$20.00,NaN,10,365,45
7989,100%,NaN,1.0,48.85685,2.30593,Paris,75007,Île-de-France,3,Entire home/apt,1.0,1.0,2.0,$99.00,$20.00,$0.00,5,365,195
7990,100%,NaN,1.0,48.83289,2.31723,Paris,75014,IDF,4,Entire home/apt,1.0,1.0,2.0,$85.00,NaN,NaN,3,100,42
7991,98%,NaN,25.0,48.85221,2.38447,Paris,75011,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$59.00,$50.00,$900.00,30,1125,32
7992,100%,NaN,1.0,48.87822,2.35769,Paris,75010,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$100.00,$40.00,$200.00,4,60,45
7993,100%,NaN,1.0,48.84723,2.37772,Paris,75012,Île-de-France,6,Entire home/apt,2.0,1.0,3.0,$135.00,$30.00,$500.00,2,1125,114
7994,NaN,NaN,1.0,48.85839,2.37744,Paris,75011,Île-de-France,4,Entire home/apt,1.0,1.0,2.0,$110.00,$50.00,NaN,3,10,0
7995,100%,NaN,2.0,48.87901,2.29526,Paris,75017,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$55.00,$45.00,$400.00,150,1125,0
7996,NaN,NaN,1.0,48.88903,2.35271,Paris,75018,Île-de-France,4,Entire home/apt,1.0,1.0,2.0,$60.00,$20.00,$100.00,3,1125,4
7997,100%,NaN,1.0,48.85313,2.34146,Paris,75006,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$60.00,$30.00,$0.00,2,10,25
7998,NaN,NaN,1.0,48.88066,2.33639,Paris,75009,Île-de-France,2,Entire home/apt,NaN,1.0,1.0,$58.00,NaN,$200.00,3,9,57
7999,100%,NaN,2.0,48.85760,2.39946,Paris,75020,Île-de-France,6,Entire home/apt,1.0,1.0,3.0,$40.00,$35.00,$300.00,4,1125,49

In [6]:
airbnb[0:10] #Affiche les 10 premieres colonnes

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173
2,100%,NaN,2.0,48.85758,2.35275,Paris,75004,Île-de-France,4,Entire home/apt,2.0,1.0,2.0,$115.00,$50.00,$200.00,10,23,243
3,100%,NaN,1.0,48.86528,2.39326,Paris,75020,Ile-de-France,3,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,365,1
4,67%,NaN,3.0,48.85899,2.34735,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$200.00,"$1,500.00",180,365,0
5,100%,NaN,1.0,48.86227,2.37134,Paris,75011,Ile-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$20.00,$250.00,5,120,17
6,NaN,NaN,4.0,48.88902,2.34656,Paris,75018,Ile-de-France,4,Entire home/apt,NaN,1.0,1.0,$80.00,$36.00,$800.00,90,730,42
7,NaN,NaN,4.0,48.88918,2.34490,Paris,75018,Ile-de-France,3,Entire home/apt,NaN,1.0,1.0,$75.00,NaN,$400.00,30,730,16
8,100%,NaN,1.0,48.87900,2.31608,Paris,75008,Ile-de-France,4,Entire home/apt,1.0,1.0,2.0,$90.00,$60.00,$600.00,3,730,40
9,100%,NaN,2.0,48.84670,2.35095,Paris,75005,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$75.00,NaN,NaN,2,1125,336

In [7]:
airbnb.iloc[0:10] #IDEM

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173
2,100%,NaN,2.0,48.85758,2.35275,Paris,75004,Île-de-France,4,Entire home/apt,2.0,1.0,2.0,$115.00,$50.00,$200.00,10,23,243
3,100%,NaN,1.0,48.86528,2.39326,Paris,75020,Ile-de-France,3,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,365,1
4,67%,NaN,3.0,48.85899,2.34735,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$200.00,"$1,500.00",180,365,0
5,100%,NaN,1.0,48.86227,2.37134,Paris,75011,Ile-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$20.00,$250.00,5,120,17
6,NaN,NaN,4.0,48.88902,2.34656,Paris,75018,Ile-de-France,4,Entire home/apt,NaN,1.0,1.0,$80.00,$36.00,$800.00,90,730,42
7,NaN,NaN,4.0,48.88918,2.34490,Paris,75018,Ile-de-France,3,Entire home/apt,NaN,1.0,1.0,$75.00,NaN,$400.00,30,730,16
8,100%,NaN,1.0,48.87900,2.31608,Paris,75008,Ile-de-France,4,Entire home/apt,1.0,1.0,2.0,$90.00,$60.00,$600.00,3,730,40
9,100%,NaN,2.0,48.84670,2.35095,Paris,75005,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$75.00,NaN,NaN,2,1125,336

In [8]:
airbnb.head() #Affiche les 5 premieres colonnes

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173
2,100%,NaN,2.0,48.85758,2.35275,Paris,75004,Île-de-France,4,Entire home/apt,2.0,1.0,2.0,$115.00,$50.00,$200.00,10,23,243
3,100%,NaN,1.0,48.86528,2.39326,Paris,75020,Ile-de-France,3,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,365,1
4,67%,NaN,3.0,48.85899,2.34735,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$200.00,"$1,500.00",180,365,0

In [9]:
 airbnb.head(2) #Affiche les 2 premieres

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173

In [10]:
airbnb.tail() #Affiche les 5 dernières

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
7995,100%,NaN,2.0,48.87901,2.29526,Paris,75017,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$55.00,$45.00,$400.00,150,1125,0
7996,NaN,NaN,1.0,48.88903,2.35271,Paris,75018,Île-de-France,4,Entire home/apt,1.0,1.0,2.0,$60.00,$20.00,$100.00,3,1125,4
7997,100%,NaN,1.0,48.85313,2.34146,Paris,75006,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$60.00,$30.00,$0.00,2,10,25
7998,NaN,NaN,1.0,48.88066,2.33639,Paris,75009,Île-de-France,2,Entire home/apt,NaN,1.0,1.0,$58.00,NaN,$200.00,3,9,57
7999,100%,NaN,2.0,48.85760,2.39946,Paris,75020,Île-de-France,6,Entire home/apt,1.0,1.0,3.0,$40.00,$35.00,$300.00,4,1125,49

In [11]:
airbnb.info() #info sur notre fichier

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
host_response_rate      5000 non-null object
host_acceptance_rate    0 non-null float64
host_listings_count     7999 non-null float64
latitude                8000 non-null float64
longitude               8000 non-null float64
city                    7997 non-null object
zipcode                 7930 non-null object
state                   7977 non-null object
accommodates            8000 non-null int64
room_type               8000 non-null object
bedrooms                7976 non-null float64
bathrooms               7942 non-null float64
beds                    7986 non-null float64
price                   8000 non-null object
cleaning_fee            6250 non-null object
security_deposit        6320 non-null object
minimum_nights          8000 non-null int64
maximum_nights          8000 non-null int64
number_of_reviews       8000 non-null int64
dtypes: float64(7), int64(4), object(8)
memory usage: 1.2+ MB

In [12]:
airbnb['beds'] #affiche les infos liés à la catégorie bed

0       0.0
1       1.0
2       2.0
3       1.0
4       1.0
5       1.0
6       1.0
7       1.0
8       2.0
9       1.0
10      3.0
11      1.0
12      1.0
13      1.0
14      2.0
15      1.0
16      3.0
17      1.0
18      0.0
19      3.0
20      1.0
21      2.0
22      2.0
23      1.0
24      2.0
25      1.0
26      1.0
27      2.0
28      1.0
29      2.0
       ...
7970    1.0
7971    4.0
7972    1.0
7973    3.0
7974    1.0
7975    1.0
7976    5.0
7977    1.0
7978    4.0
7979    3.0
7980    1.0
7981    1.0
7982    1.0
7983    1.0
7984    3.0
7985    1.0
7986    2.0
7987    2.0
7988    1.0
7989    2.0
7990    2.0
7991    1.0
7992    1.0
7993    3.0
7994    2.0
7995    1.0
7996    2.0
7997    1.0
7998    1.0
7999    3.0
Name: beds, Length: 8000, dtype: float64

In [16]:
type(airbnb[['beds', 'bedrooms']]) #Connaitre le type de ce que l'on recherche (ici DataFrame)

pandas.core.frame.DataFrame

In [17]:
type(airbnb['beds']) #ici series

pandas.core.series.Series

In [18]:
airbnb[['beds', 'bedrooms']].mean() #Moyenne de beds et bedrooms (pour dataFrame)

beds        1.753068
bedrooms    1.248370
dtype: float64

In [19]:
np.mean(airbnb['beds']) #moyenne de beds pour une série

1.753067868770348

In [20]:
airbnb_cols = airbnb.select_dtypes(include=['float']).columns.to_list() #Selectionne les éléments étant en float et organise
#les colonnes en liste

In [21]:
for col in airbnb_cols:
    calc_mean = np.mean(airbnb[col])
    print('moyenne de la colonne ' + col + ':', calc_mean)

moyenne de la colonne host_acceptance_rate: nan
moyenne de la colonne host_listings_count: 7.025878234779348
moyenne de la colonne latitude: 48.86456040249989
moyenne de la colonne longitude: 2.3487392574999952
moyenne de la colonne bedrooms: 1.248370110330993
moyenne de la colonne bathrooms: 1.12849408209519
moyenne de la colonne beds: 1.753067868770348

In [22]:
def split_func(df):
    df1 = df.loc[0:len(df)/2]
    df2 = df.loc[len(df)/2:]
    return(df1, df2)

airbnb1, airbnb2 = split_func(airbnb)

In [23]:
airbnb1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4001 entries, 0 to 4000
Data columns (total 19 columns):
host_response_rate      2845 non-null object
host_acceptance_rate    0 non-null float64
host_listings_count     4000 non-null float64
latitude                4001 non-null float64
longitude               4001 non-null float64
city                    3999 non-null object
zipcode                 3975 non-null object
state                   3983 non-null object
accommodates            4001 non-null int64
room_type               4001 non-null object
bedrooms                3983 non-null float64
bathrooms               3944 non-null float64
beds                    3988 non-null float64
price                   4001 non-null object
cleaning_fee            3255 non-null object
security_deposit        3330 non-null object
minimum_nights          4001 non-null int64
maximum_nights          4001 non-null int64
number_of_reviews       4001 non-null int64
dtypes: float64(7), int64(4), object(8)
memory usage: 594.0+ KB

In [24]:
airbnb_cols

['host_acceptance_rate',
 'host_listings_count',
 'latitude',
 'longitude',
 'bedrooms',
 'bathrooms',
 'beds']

In [25]:
airbnb[airbnb_cols]

,host_acceptance_rate,host_listings_count,latitude,longitude,bedrooms,bathrooms,beds
0,NaN,1.0,48.83349,2.31852,0.0,1.0,0.0
1,NaN,1.0,48.85100,2.35869,0.0,1.0,1.0
2,NaN,2.0,48.85758,2.35275,2.0,1.0,2.0
3,NaN,1.0,48.86528,2.39326,1.0,1.0,1.0
4,NaN,3.0,48.85899,2.34735,1.0,1.0,1.0
5,NaN,1.0,48.86227,2.37134,1.0,1.0,1.0
6,NaN,4.0,48.88902,2.34656,NaN,1.0,1.0
7,NaN,4.0,48.88918,2.34490,NaN,1.0,1.0
8,NaN,1.0,48.87900,2.31608,1.0,1.0,2.0
9,NaN,2.0,48.84670,2.35095,0.0,1.0,1.0
10,NaN,2.0,48.87110,2.37424,1.0,1.0,3.0
11,NaN,1.0,48.88434,2.34005,1.0,1.0,1.0
12,NaN,1.0,48.86350,2.36961,NaN,1.0,1.0
13,NaN,1.0,48.82405,2.36828,1.0,1.0,1.0
14,NaN,1.0,48.86578,2.37705,0.0,1.0,2.0
15,NaN,2.0,48.85090,2.38695,1.0,1.0,1.0
16,NaN,1.0,48.85909,2.37704,2.0,1.0,3.0
17,NaN,1.0,48.88315,2.34158,1.0,1.0,1.0
18,NaN,1.0,48.89052,2.34453,0.0,1.0,0.0
19,NaN,2.0,48.83616,2.36323,1.0,1.0,3.0
20,NaN,2.0,48.85339,2.36284,1.0,1.0,1.0
21,NaN,9.0,48.85324,2.34171,1.0,1.5,2.0
22,NaN,3.0,48.87033,2.37152,2.0,1.0,2.0
23,NaN,1.0,48.87217,2.36206,1.0,1.0,1.0
24,NaN,2.0,48.88282,2.33272,2.0,1.0,2.0
25,NaN,2.0,48.88327,2.33292,1.0,1.5,1.0
26,NaN,1.0,48.86093,2.34254,1.0,1.5,1.0
27,NaN,2.0,48.89001,2.34584,1.0,1.0,2.0
28,NaN,2.0,48.88308,2.33283,0.0,1.0,1.0
29,NaN,1.0,48.88565,2.35906,1.0,1.0,2.0
...,...,...,...,...,...,...,...
7970,NaN,1.0,48.86816,2.38444,1.0,1.0,1.0
7971,NaN,1.0,48.88212,2.34903,3.0,1.0,4.0
7972,NaN,1.0,48.85750,2.27467,1.0,1.0,1.0
7973,NaN,1.0,48.82203,2.32209,2.0,1.0,3.0
7974,NaN,1.0,48.87130,2.39275,1.0,1.0,1.0
7975,NaN,1.0,48.86606,2.33127,1.0,1.0,1.0
7976,NaN,1.0,48.84375,2.34960,3.0,2.0,5.0
7977,NaN,1.0,48.86218,2.40732,1.0,1.0,1.0
7978,NaN,1.0,48.87562,2.38388,2.0,1.0,4.0
7979,NaN,1.0,48.84657,2.38435,1.0,1.0,3.0
7980,NaN,1.0,48.84841,2.37941,1.0,1.0,1.0
7981,NaN,1.0,48.87573,2.34558,0.0,1.0,1.0
7982,NaN,1.0,48.85511,2.33901,1.0,1.0,1.0
7983,NaN,1.0,48.86697,2.36327,1.0,1.5,1.0
7984,NaN,1.0,48.87203,2.30208,3.0,2.0,3.0
7985,NaN,1.0,48.88641,2.33871,0.0,1.0,1.0
7986,NaN,1.0,48.86606,2.34847,2.0,1.0,2.0
7987,NaN,1.0,48.85442,2.37354,1.0,1.0,2.0
7988,NaN,2.0,48.83111,2.35257,0.0,1.0,1.0
7989,NaN,1.0,48.85685,2.30593,1.0,1.0,2.0
7990,NaN,1.0,48.83289,2.31723,1.0,1.0,2.0
7991,NaN,25.0,48.85221,2.38447,0.0,1.0,1.0
7992,NaN,1.0,48.87822,2.35769,1.0,1.0,1.0
7993,NaN,1.0,48.84723,2.37772,2.0,1.0,3.0
7994,NaN,1.0,48.85839,2.37744,1.0,1.0,2.0
7995,NaN,2.0,48.87901,2.29526,0.0,1.0,1.0
7996,NaN,1.0,48.88903,2.35271,1.0,1.0,2.0
7997,NaN,1.0,48.85313,2.34146,1.0,1.0,1.0
7998,NaN,1.0,48.88066,2.33639,NaN,1.0,1.0
7999,NaN,2.0,48.85760,2.39946,1.0,1.0,3.0

In [26]:
def add_hundred(x):
    return x+100

airbnb[airbnb_cols].apply(add_hundred)

,host_acceptance_rate,host_listings_count,latitude,longitude,bedrooms,bathrooms,beds
0,NaN,101.0,148.83349,102.31852,100.0,101.0,100.0
1,NaN,101.0,148.85100,102.35869,100.0,101.0,101.0
2,NaN,102.0,148.85758,102.35275,102.0,101.0,102.0
3,NaN,101.0,148.86528,102.39326,101.0,101.0,101.0
4,NaN,103.0,148.85899,102.34735,101.0,101.0,101.0
5,NaN,101.0,148.86227,102.37134,101.0,101.0,101.0
6,NaN,104.0,148.88902,102.34656,NaN,101.0,101.0
7,NaN,104.0,148.88918,102.34490,NaN,101.0,101.0
8,NaN,101.0,148.87900,102.31608,101.0,101.0,102.0
9,NaN,102.0,148.84670,102.35095,100.0,101.0,101.0
10,NaN,102.0,148.87110,102.37424,101.0,101.0,103.0
11,NaN,101.0,148.88434,102.34005,101.0,101.0,101.0
12,NaN,101.0,148.86350,102.36961,NaN,101.0,101.0
13,NaN,101.0,148.82405,102.36828,101.0,101.0,101.0
14,NaN,101.0,148.86578,102.37705,100.0,101.0,102.0
15,NaN,102.0,148.85090,102.38695,101.0,101.0,101.0
16,NaN,101.0,148.85909,102.37704,102.0,101.0,103.0
17,NaN,101.0,148.88315,102.34158,101.0,101.0,101.0
18,NaN,101.0,148.89052,102.34453,100.0,101.0,100.0
19,NaN,102.0,148.83616,102.36323,101.0,101.0,103.0
20,NaN,102.0,148.85339,102.36284,101.0,101.0,101.0
21,NaN,109.0,148.85324,102.34171,101.0,101.5,102.0
22,NaN,103.0,148.87033,102.37152,102.0,101.0,102.0
23,NaN,101.0,148.87217,102.36206,101.0,101.0,101.0
24,NaN,102.0,148.88282,102.33272,102.0,101.0,102.0
25,NaN,102.0,148.88327,102.33292,101.0,101.5,101.0
26,NaN,101.0,148.86093,102.34254,101.0,101.5,101.0
27,NaN,102.0,148.89001,102.34584,101.0,101.0,102.0
28,NaN,102.0,148.88308,102.33283,100.0,101.0,101.0
29,NaN,101.0,148.88565,102.35906,101.0,101.0,102.0
...,...,...,...,...,...,...,...
7970,NaN,101.0,148.86816,102.38444,101.0,101.0,101.0
7971,NaN,101.0,148.88212,102.34903,103.0,101.0,104.0
7972,NaN,101.0,148.85750,102.27467,101.0,101.0,101.0
7973,NaN,101.0,148.82203,102.32209,102.0,101.0,103.0
7974,NaN,101.0,148.87130,102.39275,101.0,101.0,101.0
7975,NaN,101.0,148.86606,102.33127,101.0,101.0,101.0
7976,NaN,101.0,148.84375,102.34960,103.0,102.0,105.0
7977,NaN,101.0,148.86218,102.40732,101.0,101.0,101.0
7978,NaN,101.0,148.87562,102.38388,102.0,101.0,104.0
7979,NaN,101.0,148.84657,102.38435,101.0,101.0,103.0
7980,NaN,101.0,148.84841,102.37941,101.0,101.0,101.0
7981,NaN,101.0,148.87573,102.34558,100.0,101.0,101.0
7982,NaN,101.0,148.85511,102.33901,101.0,101.0,101.0
7983,NaN,101.0,148.86697,102.36327,101.0,101.5,101.0
7984,NaN,101.0,148.87203,102.30208,103.0,102.0,103.0
7985,NaN,101.0,148.88641,102.33871,100.0,101.0,101.0
7986,NaN,101.0,148.86606,102.34847,102.0,101.0,102.0
7987,NaN,101.0,148.85442,102.37354,101.0,101.0,102.0
7988,NaN,102.0,148.83111,102.35257,100.0,101.0,101.0
7989,NaN,101.0,148.85685,102.30593,101.0,101.0,102.0
7990,NaN,101.0,148.83289,102.31723,101.0,101.0,102.0
7991,NaN,125.0,148.85221,102.38447,100.0,101.0,101.0
7992,NaN,101.0,148.87822,102.35769,101.0,101.0,101.0
7993,NaN,101.0,148.84723,102.37772,102.0,101.0,103.0
7994,NaN,101.0,148.85839,102.37744,101.0,101.0,102.0
7995,NaN,102.0,148.87901,102.29526,100.0,101.0,101.0
7996,NaN,101.0,148.88903,102.35271,101.0,101.0,102.0
7997,NaN,101.0,148.85313,102.34146,101.0,101.0,101.0
7998,NaN,101.0,148.88066,102.33639,NaN,101.0,101.0
7999,NaN,102.0,148.85760,102.39946,101.0,101.0,103.0

In [38]:
airbnb[airbnb_cols].apply(lambda x: x+300)

,host_acceptance_rate,host_listings_count,latitude,longitude,bedrooms,bathrooms,beds
0,NaN,301.0,348.83349,302.31852,300.0,301.0,300.0
1,NaN,301.0,348.85100,302.35869,300.0,301.0,301.0
2,NaN,302.0,348.85758,302.35275,302.0,301.0,302.0
3,NaN,301.0,348.86528,302.39326,301.0,301.0,301.0
4,NaN,303.0,348.85899,302.34735,301.0,301.0,301.0
5,NaN,301.0,348.86227,302.37134,301.0,301.0,301.0
6,NaN,304.0,348.88902,302.34656,NaN,301.0,301.0
7,NaN,304.0,348.88918,302.34490,NaN,301.0,301.0
8,NaN,301.0,348.87900,302.31608,301.0,301.0,302.0
9,NaN,302.0,348.84670,302.35095,300.0,301.0,301.0
10,NaN,302.0,348.87110,302.37424,301.0,301.0,303.0
11,NaN,301.0,348.88434,302.34005,301.0,301.0,301.0
12,NaN,301.0,348.86350,302.36961,NaN,301.0,301.0
13,NaN,301.0,348.82405,302.36828,301.0,301.0,301.0
14,NaN,301.0,348.86578,302.37705,300.0,301.0,302.0
15,NaN,302.0,348.85090,302.38695,301.0,301.0,301.0
16,NaN,301.0,348.85909,302.37704,302.0,301.0,303.0
17,NaN,301.0,348.88315,302.34158,301.0,301.0,301.0
18,NaN,301.0,348.89052,302.34453,300.0,301.0,300.0
19,NaN,302.0,348.83616,302.36323,301.0,301.0,303.0
20,NaN,302.0,348.85339,302.36284,301.0,301.0,301.0
21,NaN,309.0,348.85324,302.34171,301.0,301.5,302.0
22,NaN,303.0,348.87033,302.37152,302.0,301.0,302.0
23,NaN,301.0,348.87217,302.36206,301.0,301.0,301.0
24,NaN,302.0,348.88282,302.33272,302.0,301.0,302.0
25,NaN,302.0,348.88327,302.33292,301.0,301.5,301.0
26,NaN,301.0,348.86093,302.34254,301.0,301.5,301.0
27,NaN,302.0,348.89001,302.34584,301.0,301.0,302.0
28,NaN,302.0,348.88308,302.33283,300.0,301.0,301.0
29,NaN,301.0,348.88565,302.35906,301.0,301.0,302.0
...,...,...,...,...,...,...,...
7970,NaN,301.0,348.86816,302.38444,301.0,301.0,301.0
7971,NaN,301.0,348.88212,302.34903,303.0,301.0,304.0
7972,NaN,301.0,348.85750,302.27467,301.0,301.0,301.0
7973,NaN,301.0,348.82203,302.32209,302.0,301.0,303.0
7974,NaN,301.0,348.87130,302.39275,301.0,301.0,301.0
7975,NaN,301.0,348.86606,302.33127,301.0,301.0,301.0
7976,NaN,301.0,348.84375,302.34960,303.0,302.0,305.0
7977,NaN,301.0,348.86218,302.40732,301.0,301.0,301.0
7978,NaN,301.0,348.87562,302.38388,302.0,301.0,304.0
7979,NaN,301.0,348.84657,302.38435,301.0,301.0,303.0
7980,NaN,301.0,348.84841,302.37941,301.0,301.0,301.0
7981,NaN,301.0,348.87573,302.34558,300.0,301.0,301.0
7982,NaN,301.0,348.85511,302.33901,301.0,301.0,301.0
7983,NaN,301.0,348.86697,302.36327,301.0,301.5,301.0
7984,NaN,301.0,348.87203,302.30208,303.0,302.0,303.0
7985,NaN,301.0,348.88641,302.33871,300.0,301.0,301.0
7986,NaN,301.0,348.86606,302.34847,302.0,301.0,302.0
7987,NaN,301.0,348.85442,302.37354,301.0,301.0,302.0
7988,NaN,302.0,348.83111,302.35257,300.0,301.0,301.0
7989,NaN,301.0,348.85685,302.30593,301.0,301.0,302.0
7990,NaN,301.0,348.83289,302.31723,301.0,301.0,302.0
7991,NaN,325.0,348.85221,302.38447,300.0,301.0,301.0
7992,NaN,301.0,348.87822,302.35769,301.0,301.0,301.0
7993,NaN,301.0,348.84723,302.37772,302.0,301.0,303.0
7994,NaN,301.0,348.85839,302.37744,301.0,301.0,302.0
7995,NaN,302.0,348.87901,302.29526,300.0,301.0,301.0
7996,NaN,301.0,348.88903,302.35271,301.0,301.0,302.0
7997,NaN,301.0,348.85313,302.34146,301.0,301.0,301.0
7998,NaN,301.0,348.88066,302.33639,NaN,301.0,301.0
7999,NaN,302.0,348.85760,302.39946,301.0,301.0,303.0